# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6feb2817e587647ed9400bae56062dde66c7fd7ba52b742ef971145df5df167a95d838167c4a18b660db3ce21e588910865b3f06e2c07ffe5b148f82f716529

test:
  secret_key_base: 5fc3653c2537eba40a457b3b8cbb6ce0a484715cdd188ecd0e4a7b99eace8d0ad996229105abf8f024af6d84cec3980064a14fab105a117d1ca73a9c59f476e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
